notification/urls.py
from django.conf.urls.defaults import patterns, include, url

urlpatterns = patterns('notification',
    url(r'^$', "views.index"),
    url(r'^groups', "views.groups"),
    url(r'^manage', "views.mgmt"),  
)

npg/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.simple import redirect_to
from django.contrib.auth.decorators import login_required


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'npg.views.home', name='home'),
	# url(r'^npg/', include('npg.foo.urls')),
	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/', include(admin.site.urls)),
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	#url(r'', include('web.urls')),
	url(r'^', include('authenticate.urls')),
	url(r'^services/', include('soap.urls')),
	url(r'^request/', include('web.urls')),
	url(r'^reports/', include('reports.urls')),
	url(r'^forkyone/', include('forker.urls')),
	url(r'^timers/', include('timers.urls')),

	url(r'^nptypes.xsd$', "soap.expose_xsd.send_file"),
	
	# Uncomment the next line to enable the admin:
	# url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STORAGE_URL, document_root=settings.STORAGE_ROOT)

notification/models.py
from django.db import models
from django.forms import ModelForm
from django import forms


ALERTS = (
          ('Email','Email'),
          ('SMS','SMS'),
          ("Groups","Groups"),          
          )

TRANSPORT = (
          ('Email','Email'),
          ('SMS','SMS'),
          )

DIRECTION = (
          ('Sent','Sent'),
          ('Received','Received'),
          )

NPMESSAGES = (            
          ('NPRequest','NPRequest'),
          ('NPRequestCancel','NPRequestCancel'),
          ('NPDonorReject','NPDonorReject'),
          ('NPDonorAccept','NPDonorAccept'),
          
          ('NPExecutionCancel','NPExecutionCancel'),
          ('NPExecution','NPExecution'),
          ('NPReturn','NPReturn'),
          ('NPReturnExecution','NPReturnExecution'),
          
          ('NPBillingResolution','NPBillingResolution'),
          ('NPBillingResolutionEnd','NPBillingResolutionEnd'),
          ('NPBillingResolutionReceived','NPBillingResolutionReceived'),
          ('NPBillingResolutionAlert','NPBillingResolutionAlert'),
          
          ('NPBillingResolutionAlertReceived','NPBillingResolutionAlertReceived'),
          ('NPBillingResolutionError','NPBillingResolutionError'),
          )

class Alert(models.Model):
        
    npmessages = models.CharField(max_length=40, choices= NPMESSAGES , blank=False, null=False)
    direction = models.CharField(max_length=10, choices= DIRECTION , blank=False, null=False)
    group = models.CharField(max_length=50, blank=True, null=True)
    time = models.CharField(max_length=20, blank=True, null=True)
    message = models.CharField(max_length = 140, blank=False, null=False)
    
class Groups(models.Model):
    
    group_name  = models.CharField(max_length=20, blank=True, null=True)
    rcpt_name   = models.CharField(max_length=20, blank=False, null=False)
    type        = models.CharField(max_length=10, choices= TRANSPORT , blank=False, null=False)
    email_phone = models.CharField(max_length=50, blank=True, null=True)

class Status(models.Model):
    
    phone    = models.IntegerField(max_length=13,blank=True, null=True)
    email    = models.EmailField(blank=True, null=True)
    npmessages = models.CharField(max_length=40, choices= NPMESSAGES , blank=False, null=False)
    group    = models.CharField(max_length=20, blank=True, null=True)
    message = models.CharField(max_length = 140, blank=False, null=False)
    time     = models.DateTimeField(auto_now_add=True)
 
    
class alert_form(ModelForm):
    # Initial didn't work when attrs has been added to forms.Select, adding an empty tuple solved it
    #npmessages = forms.ChoiceField(widget=forms.Select(attrs={'class':'input-large'}),choices= NPMESSAGES, )
    
    class Meta:
        model = Alert
        fields = ('npmessages','direction','group','time','message')    
        
class groups_form(ModelForm):
    
    groups = forms.CharField(required=True)
    
    class Meta:        
        model = Groups
        fields = ('group_name', 'rcpt_name', 'type', 'email_phone')
        
class delete_group(forms.Form):
    #groups = forms.ChoiceField(widget=forms.Select(attrs={'class':'input-large'}),choices= NPMESSAGES, )
    groups = forms.CharField()
    
class delete_user(forms.Form):
    email_phone = forms.CharField()
    group_user  = forms.CharField()   

notification/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render_to_response, redirect
from django.template import RequestContext

# Models
from notification.models import Alert, Groups
# ModelForms
from notification.models import alert_form, groups_form, delete_group, delete_user

def index(request):
    form = alert_form()
    db_groups = Groups.objects.all()
    
    if request.POST:
        form = alert_form(request.POST)

        if form.is_valid():
            form.group = form.cleaned_data['group']
            form.direction = form.cleaned_data['direction']
            form.npmessages = form.cleaned_data['npmessages']
            form.message = form.cleaned_data['message']
            form.time = form.cleaned_data['time']
            
            print 'its a valid response'
            print form
            print 'form dictionary'
            print form.__dict__
            
            form.save()

            return render_to_response("notification/alerts.html",
                                      {'form'     :  form, 
                                       'success'  : 'Alert Saved ..',
                                       'db_groups':  db_groups,
                                       }, context_instance=RequestContext(request)
                                      )
        else:
            return render_to_response("notification/alerts.html",
                                                    {
                                                     'form':form,
                                                     'db_groups':  db_groups,
                                                     }, context_instance=RequestContext(request)
                                      )
    else:
         return render_to_response("notification/alerts.html",
                                                    {
                                                     'form':form,
                                                     'db_groups':  db_groups,
                                                     }, context_instance=RequestContext(request)
                                      )
def groups(request):
    form = groups_form()
    db_groups = Groups.objects.all()
    if request.POST:
       #fields = ('group_name', 'rcpt_name', 'type', 'email_phone')
        form = groups_form(request.POST)
     
        if form.is_valid():
            # If new groups is created
            if form.cleaned_data['groups'] == 'Add New ----':
                
                # If group already exists
                if Groups.objects.filter(group_name=form.cleaned_data['group_name']).exists():
                
                    return render_to_response("notification/groups.html",
                                      {'form'     :  form, 
                                       'Error'  : 'Group already exists ...',
                                       'db_groups':  db_groups,
                                       }, 
                                      context_instance=RequestContext(request)
                                      )
                else:
                    form.group_name = form.cleaned_data['group_name']
            # If an existing group is selected 
            else:
                print 'nice place'
                print form.cleaned_data['groups']
                form.group_name = form.cleaned_data['groups']
                print form.group_name
                    
            form.rcpt_name = form.cleaned_data['rcpt_name']
            form.type = form.cleaned_data['type']
            form.email_phone = form.cleaned_data['email_phone']
            
            # For some reason form.save doesn't work here, probably becuase of the the additionaly field in the modelform
            #form.save()
            
            Group = Groups()
            Group.group_name = form.group_name
            Group.rcpt_name = form.rcpt_name
            Group.type = form.type
            Group.email_phone = form.email_phone
            
            Group.save()
            
            
            return render_to_response("notification/groups.html",
                                      {'form'     :  form, 
                                       'success'  : 'Group Saved ..',
                                       'db_groups':  db_groups,
                                       }, 
                                      context_instance=RequestContext(request)
                                      )
        else:
            return render_to_response("notification/groups.html",
                                                    {
                                                     'form':form,
                                                     'db_groups':  db_groups,
                                                     }, context_instance=RequestContext(request)
                                      )
    else:
         return render_to_response("notification/groups.html",
                                                    {
                                                     'form':form,
                                                     'db_groups':  db_groups,
                                                     }, context_instance=RequestContext(request)
                                      )  
 
def mgmt(request):
     
     db_groups = Groups.objects.all()
     
     if request.POST:
         # First button is pressed
         if 'delete_group' in request.POST:
            form = delete_group(request.POST)
            
            if form.is_valid():
                form.groups = form.cleaned_data['groups']
                print 'form groups validated'
                                                 
                # Delete all the groups with this name
                success=''
                if Groups.objects.filter(group_name=form.groups).exists():
                    Groups.objects.filter(group_name=form.groups).delete()
                    success='Group Deleted ...'
                else:
                    success = "Group Doesn't exist"    
                
                return render_to_response("notification/mgmt.html",
                                                        {
                                                         'success': success,
                                                         'form':form,
                                                         'db_groups':  db_groups,
                                                         }, context_instance=RequestContext(request)
                                          )
            # Form is not valid
            else:
                return render_to_response("notification/mgmt.html",{'db_groups':  db_groups,}, context_instance=RequestContext(request))
                
         # Second button is pressed       
         elif 'delete_user' in request.POST:
             form = delete_user(request.POST)
             
             if form.is_valid():
                 form.email_phone = form.cleaned_data['email_phone']
                 form.group_user = form.cleaned_data['group_user']
                 print 'form email phone validated'  
                 
                 # Delete a user in a group
                 success=''
                 if Groups.objects.filter(group_name=form.group_user ,email_phone=form.email_phone).exists():
                    Groups.objects.filter(group_name=form.group_user ,email_phone=form.email_phone).delete()
                    success='User In Group Deleted ...'
                 else:
                    success = "User Doesn't Exist In This Group"

                   
                 return render_to_response("notification/mgmt.html",
                                                        {
                                                         'success':success,
                                                         'form':form,
                                                         'db_groups':  db_groups,
                                                         }, context_instance=RequestContext(request)
                                              )
             # Form is not valid    
             else:
                 return render_to_response("notification/mgmt.html",{'db_groups':  db_groups,}, context_instance=RequestContext(request))
         # None of those buttons        
         else:
             return render_to_response("notification/mgmt.html",{'db_groups':  db_groups,}, context_instance=RequestContext(request))        
     
     # Form is not submitted    
     else:
         return render_to_response("notification/mgmt.html",{'db_groups':  db_groups,}, context_instance=RequestContext(request))

templates/notification/alerts.html
{% extends "web/base.html" %}

{% block head %}{% endblock %}

{% block title %}Alerts{% endblock %}
{% block script %}

{% comment %}
<script>
{% endcomment %}

$(function() {
    var $selectdrop = $('#id_alert');
    
    $selectdrop.change(function() {
        var selectValues = $("#id_alert").val();
        if (selectValues == "Groups") {
            $('.GroupList').animate( { "opacity": "show", top:"100"} , 500 );
            $('.EmailPhone').animate( { "opacity": "hide", top:"100"} , 500 );
        }
        else {
            $('.GroupList').animate( { "opacity": "hide", top:"100"} , 500 );
            $('#id_main-JointAccountID').val("");
            $('.EmailPhone').animate( { "opacity": "show", top:"100"} , 500 ); 
            $('#id_main-JointAccountID').val("");
        }
    }).trigger('change');
});

{% comment %}
</script>
{% endcomment %}

{% endblock %}

{% block content %}

 <!-- this is to remove the trailing colons -->

 <style>
 .control-group label:after {content: " ";} 
 </style>
 
 
<!-- 
	<div class="row">
		<div class="span">
			<div class="navbar navbar-inner">
				<div class="nav-collapse">
					<ul class="nav">
						<li class="active"><a href="/notification" ><strong>Alerts</strong></a></li>
						<li><a href="/notification/groups" ><strong>Groups</strong></a></li>
						<li><a href="/notification/manage" ><strong>Delete User/Group</strong></a></li>
						<li><a href="/notification/status" ><strong>Status</strong></a></li>
					</ul>
				</div>	
			</div>
		</div>	
	</div> -->
	
	<br /><br />
	
	<!-- <div class="text-error">{{ form.errors }}</div> -->
	<div class="text-success"><h5>{{ success }}</h5></div>
	
	{% if form.group.errors %}<div class="text-error"><h5>Groups {{ form.group.errors }}</h5></div>{% endif %}
	{% if form.npmessages.errors %}<div class="text-error"><h5>NP Messages {{ form.npmessages.errors }}</h5></div>{% endif %}
	{% if form.direction.errors %}<div class="text-error"><h5>Direction {{ form.direction.errors }}</h5></div>{% endif %}
	{% if form.time.errors %}<div class="text-error"><h5>Time {{ form.time.errors }}</h5></div>{% endif %}
	{% if form.message.errors %}<div class="text-error"><h5>Alert Message {{ form.message.errors }}</h5></div>{% endif %}
	
	
	<div class="pull-right">

		<div class="btn-group">
               <button class="btn  btn-primary btn-large dropdown-toggle" data-toggle="dropdown">Alert Actions <span class="caret"></span></button>
               <ul class="dropdown-menu">
                 	<li class="active"><a href="/notification" ><strong>Alerts</strong></a></li>
				<li><a href="/notification/groups" ><strong>Groups</strong></a></li>
				<li><a href="/notification/manage" ><strong>Delete User/Group</strong></a></li>
				<li><a href="/notification/status" ><strong>Status</strong></a></li>
               </ul>
           </div><!-- /btn-group -->


	</div>
	
	
	<form class="well form-horizontal" action="/notification/" method="post">	
		<div class="row">
		
			<div class="span11">
				<legend><p class="text-info"><strong>Custom Alerts</strong></p></legend>
			</div>	
		
			<div class="control-group">
								
			<!-- <div class="GroupList"> -->
				<div class="span">
					<label class="control-label" for="type"><strong>Group Name &nbsp; &nbsp;</strong></label>
				</div>
				<div class="span">
						
						<select id="id_group" name="group" class="input-large" >
						  {% if db_groups %}
						  		{% for item in db_groups %}
						  			<option>{{ item.group_name }}</option>
						  		{% endfor %}	
						  {% endif %}	
						</select>
				</div>
				
				
					<div class="span">
						<label class="control-label" for="type"><strong>NP Messages </strong></label>
					</div>
					<div class="span">
						
						<select id="id_npmessages" class="input-large" name="npmessages">
							<option value="NPRequest">NPRequest</option>
							<option value="NPRequestCancel">NPRequestCancel</option>
							<option value="NPDonorReject">NPDonorReject</option>
							<option value="NPDonorAccept">NPDonorAccept</option>
							<option value="NPExecutionCancel">NPExecutionCancel</option>
							<option value="NPExecution">NPExecution</option>
							<option value="NPReturn">NPReturn</option>
							<option value="NPReturnExecution" selected="selected">NPReturnExecution</option>
							<option value="NPBillingResolution">NPBillingResolution</option>
							<option value="NPBillingResolutionEnd">NPBillingResolutionEnd</option>
							<option value="NPBillingResolutionReceived">NPBillingResolutionReceived</option>
							<option value="NPBillingResolutionAlert">NPBillingResolutionAlert</option>
							<option value="NPBillingResolutionAlertReceived">NPBillingResolutionAlertReceived</option>
							<option value="NPBillingResolutionError">NPBillingResolutionError</option>
							</select>
					</div>	
					
				<!-- 	<div class="span">
						<label class="control-label" for="type"><strong>NP Messages </strong></label>
					</div>
					<div class="span2">
						<div class="text-error">{{ form.npmessages.errors }}</div>
							{{ form.npmessages }}
					</div>	 -->
					
			</div> <!-- closing control group -->
				
			
			
			<div class="control-group">
				
				
				<div class="span">
					<label class="control-label" for="type"><strong>Direction &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</strong></label>
				</div>
				<div class="span">
					
					<select id="id_direction" name="direction" class="input-large" >
						  <option>Sent</option>
					  	  <option>Received</option> 
					</select>
				</div>					
				
				
				<div class="span">
					<label class="control-label" for="type"><strong>Promptness&nbsp;&nbsp;&nbsp;</strong></label>
				</div>
				<div class="span">
					
					<select id="id_time" name="time" class="input-large" >
					  <option>OnTime</option>
					</select>
				</div>		
				
			</div> <!-- closing control group -->
			
			
							
			<div class="control-group">				
				
				<div class="span">
					<label class="control-label" for="type"><strong>Alert Message</strong></label>
				</div>
				
				<div class="span">
					 
					 <textarea rows="3" cols="10" id="id_message" name="message" placeholder="Your custom notification messsage here"></textarea>
				</div>
				
				<div class="offset1" style="float: right; position: relative; right: 120px; top: 15px;">
					<button type="submit" class="btn btn-large btn-danger"><strong>Save Alert</strong></button>
				</div>	
				
			<!-- 	<div class="offset1">
					<button type="submit" class="btn btn-large btn-danger offset3">Save Alert</button>
				</div> -->
				
				
				
			</div> <!-- closing control group -->
			
			
			
			
		</div> <!-- closing row -->
	</form>


{% endblock %}

templates/notification/groups.html
{% extends "web/base.html" %}

{% block head %}{% endblock %}

{% block title %}Groups{% endblock %}

{% block script %}

{% comment %}
<script>
{% endcomment %}

$(function() {
    var $selectdrop = $('#id_groups');
    
    $selectdrop.change(function() {
        var selectValues = $("#id_groups").val();
        if (selectValues == "Add New ----") {
            $('#newGroupDiv').animate( { "opacity": "show", top:"100"} , 500 );
        }
        else {
            $('#newGroupDiv').animate( { "opacity": "hide", top:"100"} , 500 );
            $('#newGroupDiv').val("");
        }
    }).trigger('change');
});

{% comment %}
</script>
{% endcomment %}

{% endblock %}

{% block content %}

<!-- <style> 
 
 body div.container  div.row  div.span {width: 100%} 
 .navbar .nav { display : inline } 
 .navbar-inner { padding-left: 0;} 

 </style> -->
 
 <!-- this is to remove the trailing colons -->
 
 <style>
 .control-group label:after {content: " ";} 
 </style> 

<!-- 	<div class="row">
		<div class="span">
			<div class="navbar navbar-inner">
				<div class="nav-collapse">
					<ul class="nav">
						<li><a href="/notification" ><strong>Alerts</strong></a></li>
						<li class="active"><a href="/notification/groups" ><strong>Groups</strong></a></li>
						<li><a href="/notification/manage" ><strong>Delete User/Group</strong></a></li>
						<li><a href="/notification/status" ><strong>Status</strong></a></li>
					</ul>
				</div>	
			</div>
		</div>	
	</div> -->
	
	<br /><br />
	
	<div class="text-success"><h5>{{ success }}</h5></div>
	<div class="text-error"><h5>{{ Error }}</h5></div>
	
	{% if form.group.errors %}<div class="text-error"><h5>Groups {{ form.group.errors }}</h5></div>{% endif %}
	{% if form.group_name.errors %}<div class="text-error"><h5>Group Name {{ form.group_name.errors }}</h5></div>{% endif %}
	{% if form.rcpt_name.errors %}<div class="text-error"><h5>Recepient Name {{ form.rcpt_name.errors }}</h5></div>{% endif %}
	{% if form.type.errors %}<div class="text-error"><h5>Type {{ form.type.errors }}</h5></div>{% endif %}
	{% if form.email_phone.errors %}<div class="text-error"><h5>Email/Phone {{ form.email_phone.errors }}</h5></div>{% endif %}
	
	<div class="pull-right">

		<div class="btn-group">
               <button class="btn  btn-primary btn-large dropdown-toggle" data-toggle="dropdown">Alert Actions <span class="caret"></span></button>
               <ul class="dropdown-menu">
                 	<li><a href="/notification" ><strong>Alerts</strong></a></li>
					<li class="active"><a href="/notification/groups" ><strong>Groups</strong></a></li>
					<li><a href="/notification/manage" ><strong>Delete User/Group</strong></a></li>
					<li><a href="/notification/status" ><strong>Status</strong></a></li>
               </ul>
           </div><!-- /btn-group -->


	</div>
	
	
	<form class="well form-horizontal" action="/notification/groups/" method="post">	
		<div class="row">
		
			<div class="span11">
				<legend><p class="text-info"><strong>Add Groups</strong></p></legend>		
			</div>		
			
			<div class="control-group">
				
				<div class="span offset2">
					<label class="control-label" for="id_groups"><strong>Groups  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;</strong></label>
				</div>
				<div class="span2">

						<select id="id_groups" name="groups" class="input-large" >
						  	<option value='Add New ----' selected>Add New ----</option>
						  	{% if db_groups %}
						  		{% for item in db_groups %}
						  			<option>{{ item.group_name }}</option>
						  		{% endfor %}	
						  	{% endif %}	
						</select>
				</div>
				
				
			</div> <!-- closing control group -->
			
			<div class="control-group" id="newGroupDiv">
				<div class="span offset2">
					<label class="control-label" for="type"><p class="text-error"><strong>Group Name &nbsp;&nbsp;&nbsp;</strong></p></label>
				</div>
				<div class="span2">
						
						<input  class="input-large" type="text" id="id_group_name" name="group_name" placeholder="Group Name"></input>
				</div>					
				
			</div>
				
						
			<div class="control-group">
				<div class="span2">
					<label class="control-label" for="type"><strong>Recipient Name &nbsp;</strong></label>
				</div>
				<div class="span1">
					
					<input type="text" id="id_rcpt_name" name="rcpt_name" class="input-medium" placeholder="Put your name here"></input>
				</div>	
					
				<div class="span2">
					<label class="control-label" for="type"><strong>Type &nbsp;</strong></label>
				</div>
				<div class="span1">
					
					<select id="type" id="id_type" name="type" class="input-small">
					  <option>Email</option>
					  <option>SMS</option> 
					</select>
				</div>	
				
				<div class="span2">
					<label class="control-label" for="type"><strong>Email/Phone &nbsp;&nbsp;</strong></label>
				</div>
				<div class="span1">
					
					<input type="text" id="id_email_phone" name="email_phone" class="input-medium" placeholder="Put your mail or phone here"></input>
				</div>
				
				<div class="span1 offset1" style="float:right;">
					<button style="height: 28px;"><i class="icon-plus"></i><Strong>Add</strong></button>
				</div>
					
			</div> <!-- closing control group -->
			
			<div class="control-group">				
			
				<div style="float:left; position:relative; left:380px;">
				<!-- <div class="offset5"> -->
					<button type="submit" class="btn btn-large btn-danger"><strong>Save Group</strong></button>
				</div>				
				
			</div> <!-- closing control group -->
	
	
		</div> <!-- closing row -->
	</form>
	
{% endblock %}	

templates/notification/mgmt.html
{% extends "web/base.html" %}

{% block head %}{% endblock %}

{% block title %}Group/Item Delete{% endblock %}


{% block content %}

 <!-- this is to remove the trailing colons -->

 <style>
 .control-group label:after {content: " ";} 
 </style>
 
 

<!-- 	<div class="row">
		<div class="span">
			<div class="navbar navbar-inner">
				<div class="nav-collapse">
					<ul class="nav">
						<li><a href="/notification" ><strong>Alerts</strong></a></li>
						<li><a href="/notification/groups" ><strong>Groups</strong></a></li>
						<li class="active"><a href="/notification/manage" ><strong>Delete User/Group</strong></a></li>
						<li><a href="/notification/status" ><strong>Status</strong></a></li>
					</ul>
				</div>	
			</div>
		</div>	
	</div> -->
	
	<br /><br />
	
	{% if form.errors %}<div class="text-error"><h5>{{ form.errors }}</h5></div>{% endif %}
	{% if success %}<div class="text-success"><h5>{{ success }}</h5></div>{% endif %}
	
	
	<div class="pull-right">

		<div class="btn-group">
               <button class="btn  btn-primary btn-large dropdown-toggle" data-toggle="dropdown">Alert Actions <span class="caret"></span></button>
               <ul class="dropdown-menu">
                 	<li><a href="/notification" ><strong>Alerts</strong></a></li>
					<li><a href="/notification/groups" ><strong>Groups</strong></a></li>
					<li class="active"><a href="/notification/manage" ><strong>Delete User/Group</strong></a></li>
					<li><a href="/notification/status" ><strong>Status</strong></a></li>
               </ul>
           </div><!-- /btn-group -->


	</div>
	
	
	<form class="well form-horizontal" action="/notification/manage/" method="post">	
		<div class="row">
		
			<div class="span11">
				<legend><p class="text-error"><strong>Remove a Group</strong></p></legend>
			</div>
			
			<div class="control-group">
				
				<div class="span offset2">
					<label class="control-label" for="type"><strong>Groups </strong></label>
				</div>

				<div class="span2">
						<select id="id_groups" name="groups" class="input-large" >
						  	<option selected>Add New ----</option>
						  	{% if db_groups %}
						  		{% for item in db_groups %}
						  			<option>{{ item.group_name }}</option>
						  		{% endfor %}	
						  	{% endif %}	
						</select>
				</div>
				<div class="span offset1">
					<button type="submit" name="delete_group" class="btn btn-primary btn-danger"><strong>Remove</strong></button>
				</div>

			</div> <!-- closing control group -->

	
			<div class="span11">
			<legend><p class="text-error"><strong>Remove an Email/Phone</strong></p></legend>
			</div>

							
						
			<div class="control-group">
			
				
				<div class="span2">
					<label class="control-label" for="id_group_user"><strong> User's Group &nbsp;&nbsp;</strong></label>
				</div>

				<div class="span2">
						<select id="id_group_user" name="group_user" class="input-large" >
						  	<option selected>Add New ----</option>
						  	{% if db_groups %}
						  		{% for item in db_groups %}
						  			<option>{{ item.group_name }}</option>
						  		{% endfor %}	
						  	{% endif %}	
						</select>
				</div>
				

				<div class="span2">
					<label class="control-label" for="type"><strong>Email/Phone &nbsp;&nbsp;</strong></label>
				</div>
				
				<div class="span2">
					<input type="text" id="id_email_phone" name="email_phone" class="input-large" placeholder="Put your mail or phone here"></input>
				</div>
				<div class="span offset1">
					<button type="submit" name="delete_user" class="btn btn-primary btn-danger"><strong>Remove</strong></button>
				</div>
												
			</div> <!-- closing control group -->
	
	
		</div> <!-- closing row -->
	</form>	
	
{% endblock %}	