npg/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.simple import redirect_to
from django.contrib.auth.decorators import login_required


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
	# Examples:
	# url(r'^$', 'npg.views.home', name='home'),
	# url(r'^npg/', include('npg.foo.urls')),
	# Uncomment the admin/doc line below to enable admin documentation:
	url(r'^admin/', include(admin.site.urls)),
	url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
	#url(r'', include('web.urls')),
	url(r'^', include('authenticate.urls')),
	url(r'^services/', include('soap.urls')),
	url(r'^request/', include('web.urls')),
	url(r'^reports/', include('reports.urls')),
	url(r'^forkyone/', include('forker.urls')),
	url(r'^timers/', include('timers.urls')),

	url(r'^nptypes.xsd$', "soap.expose_xsd.send_file"),
	
	# Uncomment the next line to enable the admin:
	# url(r'^admin/', include(admin.site.urls)),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STORAGE_URL, document_root=settings.STORAGE_ROOT)

reports/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.views.generic import DetailView, ListView
from configuration import GetConfig, LogInput
from django.contrib.auth.decorators import login_required
from views import index

urlpatterns = patterns('',
	#url(r'^$', "reports.views.index"),
	url(r'^$', login_required(index)),
)

reports/models.py
from django.db import models

# Create your models here.


class ReportsEntery(models.Model):
	REPORT_TYPE = (
		('Port Out', 'Port Out'),
		('Port IN', 'Port IN'),
		('Reject Out', 'Reject Out'),
		('Reject IN', 'Reject IN'),
	)
	REPORT_DURATION = (
		('Daily', 'Daily'),
		('Monthly', 'Monthly'),
		('Yearly', 'Yearly'),
	)
	
	EnteryID = models.AutoField(max_length=20, primary_key=True)
	timestamp = models.DateTimeField(max_length=20, auto_now=True, auto_now_add=True)
	date = models.DateField(max_length=20, auto_now_add=False)
	day = models.SmallIntegerField(max_length=5)
	month = models.SmallIntegerField(max_length=5)
	year = models.SmallIntegerField(max_length=5)
	DonorName = models.CharField("Donor Name", max_length=20, blank=True, null=True) 
	RecipientName = models.CharField("Recipient Name", max_length=20, blank=True, null=True)
	report_duration = models.CharField(max_length=20, choices = REPORT_DURATION, blank=True, null=True)
	report_type = models.CharField(max_length=20, choices = REPORT_TYPE, blank=True, null=True)
	comment = models.CharField(max_length=200, blank=True, null=True)
	complete = models.BooleanField(default=False)
	count = models.IntegerField(max_length=20)
	phone_count = models.IntegerField(max_length=50, blank=True, null=True)


	class Meta:
		db_table = "np_ReportsEntery"



'''
class ReportsCount(models.Model):

	class Meta:
		db_table = "np_reports"



	EnteryID = models.AutoField(max_length=20, primary_key=True, blank=True)
	timestamp = models.DateTimeField(max_length=20, auto_now=False, auto_now_add=False, blank=True, null=True)
	date = models.DateField(max_length=20, auto_now_add=True, blank=True, null=True)
	day = models.CharField(max_length=20, blank=True, null=True)
	month = models.CharField(max_length=20, blank=True, null=True)
	year = models.CharField(max_length=20, blank=True, null=True)
	NPRequest = models.CharField(max_length=20, blank=True, null=True)
	NPRequestCancel = models.CharField(max_length=20, blank=True, null=True)
	NPDonorReject = models.CharField(max_length=20, blank=True, null=True)
	NPDonorAccept = models.CharField(max_length=20, blank=True, null=True)
	NPExecutionCancel = models.CharField(max_length=20, blank=True, null=True)
	NPExecution = models.CharField(max_length=20, blank=True, null=True)
	NPReturn = models.CharField(max_length=20, blank=True, null=True)
	NPReturnExecution = models.CharField(max_length=20, blank=True, null=True)
	NPBillingResolution = models.CharField(max_length=20, blank=True, null=True)
	NPBillingResolutionEnd = models.CharField(max_length=20, blank=True, null=True)
	NPBillingResolutionReceived = models.CharField(max_length=20, blank=True, null=True)
	NPBillingResolutionAlert = models.CharField(max_length=20, blank=True, null=True)
	NPBillingResolutionAlertReceived = models.CharField(max_length=20, blank=True, null=True)
	NPBillingResolutionError = models.CharField(max_length=20, blank=True, null=True)
	f14t10 = models.CharField(max_length=20, blank=True, null=True)
	f14t11 = models.CharField(max_length=20, blank=True, null=True)
	f14t13 = models.CharField(max_length=20, blank=True, null=True)
	f14t12 = models.CharField(max_length=20, blank=True, null=True)
	f10t14 = models.CharField(max_length=20, blank=True, null=True)
	f10t11 = models.CharField(max_length=20, blank=True, null=True)
	f10t13 = models.CharField(max_length=20, blank=True, null=True)
	f10t12 = models.CharField(max_length=20, blank=True, null=True)
	f11t14 = models.CharField(max_length=20, blank=True, null=True)
	f11t10 = models.CharField(max_length=20, blank=True, null=True)
	f11t13 = models.CharField(max_length=20, blank=True, null=True)
	f11t12 = models.CharField(max_length=20, blank=True, null=True)
	f13t14 = models.CharField(max_length=20, blank=True, null=True)
	f13t10 = models.CharField(max_length=20, blank=True, null=True)
	f13t11 = models.CharField(max_length=20, blank=True, null=True)
	f13t12 = models.CharField(max_length=20, blank=True, null=True)
	f12t14 = models.CharField(max_length=20, blank=True, null=True)
	f12t10 = models.CharField(max_length=20, blank=True, null=True)
	f12t11 = models.CharField(max_length=20, blank=True, null=True)
	f12t13 = models.CharField(max_length=20, blank=True, null=True)
	report_type = models.CharField(max_length=20, blank=True, null=True)
'''

reports/forms.py
from django import forms
import datetime

class ReportForm(forms.Form):
	allYears = range(2013, (datetime.datetime.now().year + 1))
	YEAR_CHOICES = []
	for eachYear in allYears:
		YEAR_CHOICES.append(
			(str(eachYear), str(eachYear)),
		)
	MONTH_CHOICES = (
		#('yearly','Yearly Report'),
		#('0','All'),
		('1','01 - January'),
		('2','02 - February'),
		('3','03 - March'),
		('4','04 - April'),
		('5','05 - May'),
		('6','06 - June'),
		('7','07 - July'),
		('8','08 - August'),
		('9','09 - September'),
		('10','10 - October'),
		('11','11 - November'),
		('12','12 - December'),
	)
	REPORT_CHOICES = (
		("Port Out","Port Out"),
		("Port In","Port In"),
	)
	'''
	REPORT_CHOICES = (
		("Summary","Summary"),
		("Port Out","Port Out"),
		("Port In","Port In"),
		("Cross Porting","Cross Porting"),
		("Accepted Requests","Accepted Requests"),
		("Rejected Requests","Rejected Requests"),
	)
	'''
	ReportType = forms.ChoiceField(
		label = "Report Type", 
		choices = REPORT_CHOICES,
		initial = "Summary", 
		widget = forms.Select(),
		required = False,
	)
	Year = forms.ChoiceField(
		label = "Year", 
		choices = YEAR_CHOICES,
		initial = datetime.datetime.now().year, 
		widget = forms.Select(),
		required = False,
	)
	Month = forms.ChoiceField(
		label = "Month", 
		choices = MONTH_CHOICES,
		initial = str(datetime.datetime.now().month), 
		widget = forms.Select(),
		required = False,
	)

web/forms.py
from models import NpMessages, RoutingInfoList, DonorRejectList
from django import forms
from django.forms import ModelForm, Textarea
from django.forms.models import inlineformset_factory
from django import forms
from django.contrib.admin.widgets import AdminFileWidget
from django.forms import extras
from django.contrib.auth.models import User
from configuration import GetStatus


from datetime import datetime, date, timedelta
from npg import settings

class FilterForm(forms.Form):
	
	STATUS_CHOICES = [('', 'All Status')]
	
	for key, status in GetStatus("StatusDict").iteritems():
		if key in range(1,20):
			STATUS_CHOICES.append((str(key),status[1]))
	
	USER_CHOICES = [("","All Agent")]
	AllUsers = User.objects.all().order_by('first_name')
	for user in AllUsers:
		USER_CHOICES.append((user.username,'%s %s - %s' % (user.first_name,user.last_name,user.username)))
		
	Status = forms.ChoiceField(
		label = "Status", 
		choices = STATUS_CHOICES,
		initial = 'ALL', 
		widget = forms.Select(),
		required=False,
	)

	User = forms.ChoiceField(
		label = "Agent Name", 
		choices = USER_CHOICES,
		#initial = '0', 
		widget = forms.Select(),
		required=False,
	)
	
	PhoneNumber = forms.CharField(
		label='Phone Number', 
		#initial = "%s 03:00:00"%str(date.today()+timedelta(days=10)),
		#format = settings.DATETIME_INPUT_FORMATS,
		#widget = forms.TextInput(attrs={'readonly':'readonly'})
		required=False,
		max_length = 8,
		#widget=forms.TextInput(attrs={'maxlength':'8'}),
	)

	NPOrderID = forms.CharField(
		label='Order ID', 
		#initial = "%s 03:00:00"%str(date.today()+timedelta(days=10)),
		#format = settings.DATETIME_INPUT_FORMATS,
		#widget = forms.TextInput(attrs={'readonly':'readonly'})
		required=False,
	)

	
	class Meta:
		model = NpMessages
		fields = (
			'NPOrderID',
			'user',
		)


class SearchMessagesForm(ModelForm):
	OPERATOR_CHOICES = [
		("ALL","All"),
		("ooredoo","ooredoo"),
		("Zain","Zain"),
		("Viva","Viva"),
	]
	ORIGINATOR_CHOICES = [
		("ALL","All"),
		("NPG","NPG"),
		("NPCS","NPCS"),
	]
	ACK_CHOICES = [
		("ALL","All"),
		("ack","Acknowledged"),
		("error","Error"),
	]
	MESSAGE_TYPE_NAME_CHOICES = [
		("ALL","All"),
		("Porting Order", (
			("NPRequest","NPRequest"),
			("NPRequestConfirmation","NPRequestConfirmation"),
			("NPRequestReject","NPRequestReject"),
			("NPRequestCancel","NPRequestCancel"),
			("NPDonorReject","NPDonorReject"),
			("NPDonorAccept","NPDonorAccept"),
			("NPActivated","NPActivated"),
			("NPDeactivated","NPDeactivated"),
			("NPExecuteCancel","NPExecuteCancel"),
			("NPExecuteBroadcast","NPExecuteBroadcast"),
		)),
		("Return Numbers", (
			("NPReturn","NPReturn"),
			("NPReturnCancel","NPReturnCancel"),
			("NPReturnBroadcast","NPReturnBroadcast"),
		)),
		("Ring Fence", (
			("NPRingFenceRequest","NPRingFenceRequest"),
			("NPRingFenceDeny","NPRingFenceDeny"),
			("NPRingFenceApprove","NPRingFenceApprove"),
		)),
		("Emergency Restore", (
			("NPEmergencyRestore","NPEmergencyRestore"),
			("NPEmergencyRestoreDeny","NPEmergencyRestoreDeny"),
			("NPEmergencyRestoreApprove","NPEmergencyRestoreApprove"),
		)),
		("Others", (
			("NPFinalBillNotification","NPFinalBillNotification"),
			("MessageAck","MessageAck"),
			("ErrorNotification","ErrorNotification"),
		)),
	]

	STATUS_CHOICES = [
		('ALL', 'All Status'),
		("Porting Order", (
			("1","1 - Request Sent - Request sent waiting SMS confirmation"),
			("2","2 - Request Rejected - Request rejected invalid information"),
			("3","3 - Request Rejected - Request rejected SMS wasn't received"),
			("4","4 - Request Canceled - Request canceled"),
			("5","5 - Request Confirmed - Request confirmed by customer's SMS"),
			("6","6 - Request Rejected - Request rejected by donor"),
			("7","7 - Request Accepted - Request accepted by donor"),
			("8","8 - Request Accepted - Request auto accepted by CRDB"),
			("9","9 - Activation Request Received - Request has been activated"),
			("10","10 - Number Activated - Porting has been completed"),
			("11","11 - Request Execution Canceled - Request execution canceled"),
			("12","12 - Request Deactivated - Request has been deactivated"),
		)),
		("Return Numbers", (
			("70","70 - NPReturn Active - NPReturn Active"),
			("71","71 - NPReturn Failed - NPReturn validation failed"),
			("72","72 - NPReturn Canceled - NPReturn Canceled"),
			("73","73 - NPReturn Complete - NPReturn Complete"),
			("74","74 - NPReturn Cancel Failed - NPReturn cancel failed"),
		)),
		("Ring Fence", (
			("50","50 - Ring fence sent - New ring fence awaiting help desk approval"),
			("51","51 - Ring fence approved - Ring fence approved and active"),
			("52","52 - Ring fence failed - Ring fence validation failed"),
			("53","53 - Ring fence denied - Ring fence rejected by help desk"),
		)),
		("Emergency Restore", (
			("40","40 - Emergency Restore Active"),
			("41","41 - Emergency Restore Denied - Denied by the CRDB help desk"),
			("42","42 - Emergency Restore Approve - Approved by the CRDB help desk"),
			("43","43 - Emergency Restore failed - Emergency Restore validation failed"),
		)),
		("Others", (
			("150","150 - Waiting Internal - Waiting Internal System Update"),
			("151","151 - Agent Create Account - After account creating please activate"),
		)),
	]
	'''
	STATUS_CHOICES = [('ALL', 'All Status')]

	for key, status in GetStatus("StatusDict").iteritems():
		if key in range(1,200):
			STATUS_CHOICES.append((str(key),status[1]))
	'''
	Status = forms.ChoiceField(
		label = "Status", 
		choices = STATUS_CHOICES,
		initial = 'ALL', 
		widget = forms.Select(),
		required=False,
	)
	
	'''
	USER_CHOICES = [("","All Agent")]
	AllUsers = User.objects.all().order_by('first_name')
	for user in AllUsers:
		USER_CHOICES.append((user.username,'%s %s - %s' % (user.first_name,user.last_name,user.username)))

	User = forms.ChoiceField(
		label = "Agent Name", 
		choices = USER_CHOICES,
		widget = forms.Select(),
		required=False,
	)
	'''
	PhoneNumber = forms.CharField(
		label='Phone Number', 
		required=False,
		max_length = 8,
	)
	DateFrom = forms.DateField(
		label='From', 
		required=False,
	)
	DateTo = forms.DateField(
		label='To', 
		required=False,
	)

	ExecutionDateFrom = forms.DateField(
		label='From', 
		required=False,
	)
	ExecutionDateTo = forms.DateField(
		label='To', 
		required=False,
	)

	NPOrderID = forms.CharField(
		label='Order ID', 
		required=False,
	)
	RecipientName = forms.ChoiceField(
		label = "Recipient", 
		choices = OPERATOR_CHOICES,
		initial = 'ALL', 
		widget = forms.Select(),
		required=False,
	)
	DonorName = forms.ChoiceField(
		label = "Donor", 
		choices = OPERATOR_CHOICES,
		initial = 'ALL', 
		widget = forms.Select(),
		required=False,
	)
	Originator = forms.ChoiceField(
		label = "Originator", 
		choices = ORIGINATOR_CHOICES,
		initial = 'ALL', 
		widget = forms.Select(),
		required=False,
	)
	MessageTypeName = forms.ChoiceField(
		label = "Message", 
		choices = MESSAGE_TYPE_NAME_CHOICES,
		initial = 'ALL', 
		widget = forms.Select(),
		required=False,
	)
	ack = forms.ChoiceField(
		label = "Ack", 
		choices = ACK_CHOICES,
		initial = 'ack', 
		widget = forms.Select(),
		required=False,
	)
	class Meta:
		model = NpMessages
		fields = (
			'NPOrderID',
			'PhoneNumber',
			'MessageTypeName',
			'ack',
			'DonorName',
			'RecipientName',
			'Originator',
			'DateFrom',
			'DateTo',
			'ExecutionDateFrom',
			'ExecutionDateTo',
			'Status',
		)


class NpMessagesForm(ModelForm):
	"""
	Auto generated form to create Server models.
	"""
	class Meta:
		model = NpMessages
		## Added user and status to the fields, so we save the modelform object directly when assigning them to the instance
		#fields = ('NPOrderID','MessageTypeName', 'NumberType', 'CustomerType', 'SubscriptionType', 'CustomerName', 'CustomerID', 'UnbilledPayment', 'RecipientContactInfo', 'ExecutionTime', 'ReversalOrderID','user','status')

class EmergencyRestoreForm(ModelForm):

	class Meta:
		model = NpMessages
		fields = (
			'OriginalNPOrderID',
		)


class EmergencyRestoreForm(ModelForm):

	class Meta:
		model = NpMessages
		fields = (
			'OriginalNPOrderID',
		)

class NPRequestForm(ModelForm):
	#ExecutionTime = forms.SplitDateTimeField(label="Execution Time", input_date_formats='%d-%m-%Y', input_time_formats='%H:%M')
	'''
	ExecutionTime = forms.CharField(
		label='Execution Time', 
		initial = "%s 03:00:00"%str(date.today()+timedelta(days=10)),
		#format = settings.DATETIME_INPUT_FORMATS,
		#widget = forms.TextInput(attrs={'readonly':'readonly'})
	)
	RequestType = forms.ChoiceField(
		label = "Request Type", 
		choices = [
			('NewRequest', 'New Port IN'),
			('NewRequestBlock', 'New Block Order'),
			('EmergencyRestore', 'Emergency Restore'),
		], 
		initial = 'NewRequest', 
		widget = forms.Select()
	)
	'''
	ImmediatePorting = forms.ChoiceField(
		label = "Delayed Porting", 
		choices = [
			('now', 'Immediate Porting'),
			('delay', 'Delayed Porting'),
		], 
		initial = 'now', 
		widget = forms.Select()
	)
	SubscriptionType = forms.ChoiceField(
		label = "Subscription Type", 
		choices = [
			('prepaid', 'Prepaid'),
			('postpaid', 'Postpaid'),
		], 
		initial = 'prepaid', 
		widget = forms.Select()
	)
	CustomerType = forms.ChoiceField(
		label = "Customer Type", 
		choices = [
			('consumer', 'Consumer'),
			('business', 'Business'),
		], 
		initial = 'consumer', 
		widget = forms.Select()
	)

	CustomerIDType = forms.ChoiceField(
		label = "Customer ID Type", 
		choices = [
			(1, 'Passport'),
			(2, 'Civil ID'),
			(3, 'Company Registration Number'),
			(4, 'National ID'),
		], 
		initial = 1, 
		widget = forms.Select()
	)

	PaymentCode = forms.CharField(
		label = "Payment Code", 
		max_length = 8,
		required=False,
	)

	ValidationMSISDN = forms.CharField(
		label = "Mobile Number", 
		max_length = 8,
	)

	# Currently is set on auto Mobile
	'''
	ServiceType = forms.ChoiceField(
		label = "Service Type", 
		choices = [
			('mobile', 'Mobile'),
			('fixed', 'Fixed'),
		], 
		initial = 'mobile', 

templates/web/search_messages2.html
{% extends "web/base.html" %}

{% block title %}NPG - {{ PageName }}{% endblock %}

{% block head %}
  <link rel="stylesheet" href="/media/datepicker/jquery-ui.css" />
  <script src="/media/datepicker/jquery-1.9.1.js"></script>
  <script src="/media/datepicker/jquery-ui.js"></script>
  <link rel="stylesheet" href="/media/datepicker/style.css" />
{% endblock %}


{% block script %}

{% comment %}
<script>
{% endcomment %}
	$(function() {
		$( "#id_DateFrom" ).datepicker({
			changeMonth: true,
			
			yearRange: "2013:Y",
			maxDate: "D",
			dateFormat: 'yy-mm-dd',
		});
		$( "#id_DateTo" ).datepicker({
			changeMonth: true,
			
			yearRange: "2013:Y",
			maxDate: "D",
			dateFormat: 'yy-mm-dd',
		});
});
{% comment %}
</script>
{% endcomment %}

{% endblock %}



{% block content %}
<h3>Search Messages</h3>
<table class="table table-bordered">
	<thead>
	<tr>
		<th>{{ form.NPOrderID.label }}</th>
		<th>{{ form.PhoneNumber.label }}</th>
		<th>{{ form.DonorName.label }}</th>
		<th>{{ form.RecipientName.label }}</th>
		<th>{{ form.Originator.label }}</th>
	</tr>
	</thead>
	<tr>
	<form enctype='multipart/form-data' name='Search' id='Search' action='/request/search2/' method='post'>
		{% csrf_token %}
		<td>
			{{ form.NPOrderID }}{{ form.NPOrderID.errors }}
		</td>
		<td>
			{{ form.PhoneNumber }}{{ form.PhoneNumber.errors }}
		</td>
		<td>
			{{ form.DonorName }}{{ form.DonorName.errors }}
		</td>
		<td>
			{{ form.RecipientName }}{{ form.RecipientName.errors }}
		</td>
		<td>
			{{ form.Originator }}{{ form.Originator.errors }}
		</td>
	</tr>
</table>
<table class="table table-bordered">
	<thead>
	<tr>
		<th>{{ form.MessageTypeName.label }}</th>
		<th>From</th>
		<th>To</th>
		<th>Ack</th>
	</tr>
	<tr>
		<td>
			{{ form.MessageTypeName }}{{ form.MessageTypeName.errors }}
		</td>
		<td>
			{{ form.DateFrom }}{{ form.DateFrom.errors }}
		</td>
		<td>
			{{ form.DateTo }}{{ form.DateTo.errors }}
		</td>
		<td>
			<input type="checkbox" name="showAck" value="YES" {% if showAck == "YES" %} checked="yes"{% endif %} onChange="document.forms['Search'].submit();"/> 
		</td>
	</tr>
</table>
<table class="table table-bordered">
	<thead>
	<tr>
		<th>Status</th>
	</tr>
	<tr>
		<td>
			{{ form.Status }}{{ form.Status.errors }} 
		</td>
	</tr>
</table>
<div style="text-align:right;margin-bottom:20px">
	<input type="submit" name="SubmitType" value="Show All/Search" class="btn btn-success">&nbsp;&nbsp;&nbsp;
	<input name='ExportReportExcel'  type="submit" class="btn"    value='  Export Results - Excel  '>&nbsp;&nbsp;&nbsp;
	<input name='ExportReportCSV'  type="submit" class="btn" value='   Export Results - CSV   '>
	{% comment %}
	<input type="submit" name="SubmitType" value="Reset" class="btn">
	{% endcomment %}
</div>
</form>									


	{% if NPOrderID_list %}

	<tr>
		<td align="center" colspan="4" bgcolor="#6E6E6E" height="45" width="" bordercolor="#FFFFFF" bgcolor="white">
			<font face='Candara' size="2" color="white">Found multiple Port ID for this number: {{ form.number.value }} please choose one then click search<br>
			<table style="table" style="width:100%">
			
			{% for NPOrderID in NPOrderID_list %}
			<tr>
				<td>
					<a href="#" onclick="document.getElementById('NPOrderID').value = '{{ NPOrderID }}'; " /><font face='Candara' size="1" color="black">{{ NPOrderID }}</a>
				</td>
			</tr>
			{% endfor %}
			</table>
		</td>
	</tr>

</table>
<br>
<table align="center" border="1" cellspacing="1" style="border-collapse: collapse" width="800" cellpadding="5">

{% else %}

</table>
<br>
<table class="table" style="width:100%">

{% if SearchResults.object_list %}
<tr bgcolor="#E0E0E0">
	<td width="120" bgcolor="" align="center" valign="middle">
		{% if SearchResults.has_previous %}
			<input type="hidden" name="pageP" value="{{ SearchResults.previous_page_number }}">
			<input name='PageChangeP' type=image src="/media/previous_on.png" value='Previous'>
		{% else %}
			<img border="0" src="/media/previous_off.png" />
		{% endif %}
	</td>
	<td style="text-align:center;font-damily:Candara;;padding-top:10px">
			<span style="">Search Results</span>
			<select name="ShowTotalResults" onChange="document.forms['Search'].submit();">
				<option value="10" {% if ShowTotalResults == '10' %} selected="selected"{% endif %} >10</option>
				<option value="20" {% if ShowTotalResults == '20' %} selected="selected"{% endif %} >20</option>
				<option value="40" {% if ShowTotalResults == '40' %} selected="selected"{% endif %} >40</option>
				<option value="80" {% if ShowTotalResults == '80' %} selected="selected"{% endif %} >80</option>
			</select>
			<span style="vertical-align:middle;">
			 - Found {{ TotalSearchResults }} messages
			</span>
			{% if SearchResults.has_previous %}
			<span style="vertical-align:middle">
				 - Page {{ SearchResults.number }} of {{ SearchResults.paginator.num_pages }}
			 </span>
			 
			 
			{% else %}
			{% if SearchResults.has_next %}
			<span style="vertical-align:middle">
			 - Page {{ SearchResults.number }} of {{ SearchResults.paginator.num_pages }}
			</span>

			{% else %}
			{% endif %}
			{% endif %}
			 
	</td>
	<td width="120" bgcolor="" align="center" valign="middle">
		{% if SearchResults.has_next %}
			<input type="hidden" name="pageN" value="{{ SearchResults.next_page_number }}">
			<input name='PageChangeN' type=image src="/media/next_on.png" value='Next'>
		{% else %}
			<img border="0" src="/media/next_off.png" />
		{% endif %}
	</td> 
</tr>
</form>
{% if paginate_by %}{% load paginator %}{% paginator 3 %}{% endif %}
<table style="width:100%" class="table table-striped">
	<tr>
		<th>
			#
		</th>
		<th>
			NP Order ID
		</th>
		<th>
			Message Type
		</th>
		<th >
			Message Time
		</th>
		<th >
			Status
		</th>
		<th >
			Sender Name
		</th>
		<th>
			Recipient Name
		</th>
		<th>
			Donor Name
		</th>
		<th>
			Originator
		</th>
	</tr>
{% for message in SearchResults.object_list %}
	<tr>
		<td >
			<a href="{% if message.MessageLocalID != None %}{{ message.MessageLocalID }}{% endif %}" onclick="window.open('{% if message.MessageLocalID != None %}{{ message.MessageLocalID }}{% endif %}','popup','width=900,height=700,scrollbars=yes,resizable=yes,toolbar=no,directories=no,location=no,menubar=no,status=no,left=50,top=0'); return false">{% if message.MessageLocalID != None %}{{ message.MessageLocalID }}{% endif %}</a>
		</td>
		<td>
			{% if message.NPOrderID != None %}<a href="#" onclick="document.getElementById('NPOrderID').value = '{{ message.NPOrderID }}'; " />{{ message.NPOrderID }}{% endif %}
		</td>
		<td>
			{% if message.MessageTypeName != None %}{{ message.MessageTypeName }}{% endif %}
		</td>
		<td>
			{% if message.message_created != None %}{{ message.message_created }}{% endif %}
		</td>
		{% load GetChoice %}
		<td>
			<a  title="{{ somevariable|GetStatusDetails:message.status }}">{{ somevariable|GetStatusName:message.status }}</a>
		</td>

		<td>
			{% if message.SenderName != None %}{{ message.SenderName }}{% endif %}
		</td>
		<td>
			{% if message.RecipientName != None %}{{ message.RecipientName }}{% endif %}
		</td>
		<td>
			{% if message.DonorName != None %}{{ message.DonorName }}{% endif %}
		</td>
		<td>
			{% if message.Originator != None %}{{ message.Originator }}{% endif %}
		</td>
	</tr>
{% endfor %}
{% else %}
{% if submitted == "yes" %}
<tr>
	<td colspan="6"  width="100%" style="text-align:center">
		No Messages Found
	</td>
</tr>
{% endif %}
{% endif %}
{% endif %}
</table>
{% endblock %}